site_name: Protein Detective
repo_url: https://github.com/haddocking/protein-detective
theme: 
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
plugins:
  - search
  - mkdocs-jupyter
nav:
  - Home: index.md
  - Notebooks:
    - Retrieve: uniprot.ipynb
    - AlphaFold: alphafold.ipynb
    - PDBe: pdbe.ipynb
    - Workflow: workflow.ipynb