[project]
name = "protein_detective"
dynamic = ["version"]
description = "Deduce the protein from a EM density"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=24.1.0",
    "aiohttp[speedups]>=3.13.4",
    "aiohttp-retry>=2.9.1",
    "cyclopts>=4.16.1",
    "dask>=2025.5.1",
    "distributed>=2025.5.1",
    "duckdb>=1.2.2",
    "molviewspec>=1.6.0",
    "numpy>=2.3.1",
    "pandas>=2.3.0",
    "powerfit-em[opencl]>=5.0.0",
    "protein-quest>=1.4.0",
    "psutil>=7.0.0",
    "pyopencl>=2025.2.5",
    "rich>=14.0.0",
    "rich-argparse>=1.7.1",
    "tqdm>=4.67.1"
]

[project.urls]
Homepage = "https://github.com/haddocking/protein-detective"
Issues = "https://github.com/haddocking/protein-detective/issues"
Documentation = "https://www.bonvinlab.org/protein-detective/"
Source = "https://github.com/haddocking/protein-detective"

[project.scripts]
protein-detective = "protein_detective.cli:main"

[project.optional-dependencies]
cuda13 = [
    "powerfit-em[cuda13x]>=5.0.0",
]
cuda12 = [
    "powerfit-em[cuda12x]>=5.0.0",
]

[dependency-groups]
type = [
    "pyrefly>=1.1.1",
    "types-aiofiles>=24.1.0.20250326",
    "types-tqdm>=4.67.0.20250513"
]
test = [
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
]
dev = [
    {include-group = "test"},
    {include-group = "type"}
]
docs = [
    "cyclopts[mkdocs]>=4.5.4",
    "duckdb-engine>=0.17.0",
    "gemmi>=0.7.3",
    "ipykernel>=6.31.0",
    "ipywidgets>=8.1.7",
    "jupysql>=0.11.1",
    "matplotlib>=3.10.3",
    "mkdocs>=1.6.1",
    "mkdocs-autoapi>=0.4.1",
    "mkdocs-jupyter>=0.25.1",
    "mkdocs-material>=9.6.22",
    "mkdocstrings[python]>=0.30.1",
    "nbconvert>=7.16.6"
]

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/protein_detective/__version__.py"

[tool.ruff]
line-length = 120
extend-include = ["*.ipynb"]

[tool.ruff.lint]
select = [
    "A",
    # TODO enable ANN and make code more typed
    # "ANN",
    "ARG",
    "B",
    "BLE",
    "C",
    # TODO enable D and make code more descriptive
    # "D",
    "D417",
    "DTZ",
    "E",
    "EM",
    "ERA",
    "F",
    # TODO enable FBT and factor out booleans args to seperate functions
    # "FBT",
    "FURB",
    "I",
    "ICN",
    "ISC",
    "LOG",
    "N",
    # TODO enable NPT and use modern random
    # "NPY",
    "PD",
    "PERF",
    "PGH",
    "PLC",
    "PLE",
    # TODO enable PLR and make code less complex
    # "PLR",
    # TODO enable PT for tests/**
    # "PT",
    "PTH",
    "PLW",
    "Q",
    "RET",
    "RSE",
    "RUF",
    "S",
    "SLOT",
    "SIM",
    "T",
    "TCH",
    "TID",
    "TRY",
    "UP",
    "W",
    "YTT"
]
ignore = [
    # Conflicts with formatting
    "ISC001",
    # Conflicts with default rules
    "PLC0414",
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*" = [
    "ARG", "ANN", "D", "E501", "DTZ001", "N802", "S101", "S108", "PLR2004"
]
"docs/**/*.ipynb" = [
    # Allow wide lines in notebooks
    "E501",
    # Allow prints
    "T201",
    # Allow pprints
    "T203",
    # Allow bare async
    "PLE1142",
    # Allow generic variable name
    "PD901",
    # Allow suspicious-url-open-usage
    "S310"
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint.isort]
known-first-party = ["protein_detective"]

[tool.jupysql.SqlMagic]
displaylimit = 100

[tool.uv.sources]
protein-quest = { path = "../protein-quest", editable = true }

[tool.pyrefly]
preset = "strict"
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]

[tool.pytest]
minversion = "9.0"
addopts = [
    "--import-mode=importlib",
]

[tool.coverage.run]
source = ["src/protein_detective"]
branch = true
