from pathlib import Path
from typing import Any, cast

import pandas as pd
import pytest
from molviewspec import MVSJ, State, States
from pandas.testing import assert_frame_equal

from protein_detective.visualization import (
    load_fitted_models,
    show_fitted_models_and_density,
    show_structure_and_density,
)


def write_csv(rows: list[dict[str, str]], path: Path):
    df = pd.DataFrame(rows)
    df.to_csv(path, index=False)


def fake_session_with_fitted_models(tmp_path: Path):
    # Data copied from data generated by commands in ./README.md, with absolute paths
    fitted_models_csv = tmp_path / "fitted_models.csv"
    write_csv(
        [
            {
                "powerfit_run_id": "myrun1",
                "structure": "3i8z_updated_A2A.cif.gz",
                "rank": "1",
                "fitted_model_file": str(tmp_path / "powerfit/myrun1/3i8z_updated_A2A.cif.gz/fit_1.pdb"),
                "unfitted_model_file": str(tmp_path / "combined_output/3i8z_updated_A2A.cif.gz"),
            }
        ],
        fitted_models_csv,
    )
    report_csv = tmp_path / "report.csv"
    write_csv(
        [
            {
                "powerfit_run_id": "myrun1",
                "structure": "3i8z_updated_A2A.cif.gz",
                "rank": "1",
                "cc": "0.598",
                "fishz": "0.69",
                "relz": "12.959",
                "translation": "239.46:187.27:211.83",
                "rotation": "-0.238:0.322:0.916:0.916:-0.238:0.322:0.322:0.916:-0.238",
                "template_file": str(tmp_path / "combined_output/3i8z_updated_A2A.cif.gz"),
                "uniprot_accessions": "O00257",
                "structure_id": "3I8Z",
                "is_alphafold": "False",
            }
        ],
        report_csv,
    )
    runs_csv = tmp_path / "runs.csv"
    write_csv(
        [
            {
                "powerfit_run_id": "myrun1",
                "density_map": str(tmp_path / "powerfit/myrun1/ribosome-KsgA.map"),
                "run_dir": str(tmp_path / "powerfit/myrun1"),
                "options": "--workers-per-gpu 2 --angle 40 --powerfit-run-id myrun1 ../powerfit-tutorial/ribosome-KsgA.map 13 ./mysession",
            }
        ],
        runs_csv,
    )
    return fitted_models_csv, report_csv, runs_csv


def test_load_fitted_models(tmp_path: Path):
    fitted_models_csv, report_csv, runs_csv = fake_session_with_fitted_models(tmp_path)
    df = load_fitted_models(fitted_models_csv=fitted_models_csv, report_csv=report_csv, runs_csv=runs_csv)

    expected_df = pd.DataFrame(
        [
            {
                "powerfit_run_id": "myrun1",
                "structure": "3i8z_updated_A2A.cif.gz",
                "rank": 1,
                "fitted_model_file": str(tmp_path / "powerfit/myrun1/3i8z_updated_A2A.cif.gz/fit_1.pdb"),
                "unfitted_model_file": str(tmp_path / "combined_output/3i8z_updated_A2A.cif.gz"),
                "cc": 0.598,
                "fishz": 0.69,
                "relz": 12.959,
                "translation": [239.46, 187.27, 211.83],
                "rotation": [-0.238, 0.322, 0.916, 0.916, -0.238, 0.322, 0.322, 0.916, -0.238],
                "uniprot_accessions": ["O00257"],
                "structure_id": "3I8Z",
                "is_alphafold": False,
                "density_map": str(tmp_path / "powerfit/myrun1/ribosome-KsgA.map"),
                "run_dir": str(tmp_path / "powerfit/myrun1"),
                "options": "--workers-per-gpu 2 --angle 40 --powerfit-run-id myrun1 ../powerfit-tutorial/ribosome-KsgA.map 13 ./mysession",
            }
        ]
    )
    assert_frame_equal(df, expected_df)


def _child_urls(node: Any) -> list[str]:
    """Return the download URLs from the node's child entries."""
    assert node.children is not None
    urls: list[str] = []
    for child in node.children:
        assert child.params is not None
        url = child.params.get("url")
        assert isinstance(url, str)
        urls.append(url)
    return urls


class TestShowFittedModelsAndDensity:
    def test_invalid_renderer(self):
        df = pd.DataFrame()
        with pytest.raises(
            NotImplementedError,
            match=r"Renderer 'invalid' is not implemented\. Supported: html, notebook, streamlit, raw",
        ):
            # pyrefly: ignore [bad-argument-type]
            show_fitted_models_and_density(df, renderer="invalid")

    def test_zero_fitted_models(self):
        df = pd.DataFrame()

        state, data = show_fitted_models_and_density(df, renderer="raw")

        assert data == {}
        assert isinstance(state, MVSJ)

    def test_single_row(self, tmp_path: Path, ribosome_map: Path, ksga_pdb: Path, cif_2y29: Path):
        fitted_models_csv, report_csv, runs_csv = fake_session_with_fitted_models(tmp_path)
        unfitted_model_path = tmp_path / "combined_output/3i8z_updated_A2A.cif.gz"
        unfitted_model_path.parent.mkdir()
        unfitted_model_path.symlink_to(cif_2y29)
        density_map_path = tmp_path / "powerfit/myrun1/ribosome-KsgA.map"
        density_map_path.parent.mkdir(parents=True)
        density_map_path.symlink_to(ribosome_map)
        fitted_model = tmp_path / "powerfit/myrun1/3i8z_updated_A2A.cif.gz/fit_1.pdb"
        fitted_model.parent.mkdir()
        fitted_model.symlink_to(ksga_pdb)
        df = load_fitted_models(fitted_models_csv=fitted_models_csv, report_csv=report_csv, runs_csv=runs_csv)

        state, data = show_fitted_models_and_density(df, renderer="raw")

        expected_data = {
            str(density_map_path): ribosome_map.read_bytes(),
            str(fitted_model): ksga_pdb.read_bytes(),
        }
        assert data == expected_data
        assert isinstance(state, MVSJ)
        states = cast("States", state.data)
        assert states.metadata.description == "Fitted models and density map"
        assert len(states.snapshots) == 1
        snapshot = states.snapshots[0]
        assert snapshot.metadata.key == "myrun1-3i8z_updated_A2A.cif.gz-1"
        assert snapshot.metadata.title == "3i8z_updated_A2A.cif.gz - 1 (myrun1)"
        assert snapshot.metadata.description is not None
        description = snapshot.metadata.description
        assert description.lstrip().startswith("- Run: myrun1")
        assert "Cross correlation score: 0.60" in description
        assert "PDB ID: [3I8Z]" in description
        assert _child_urls(snapshot.root) == [str(density_map_path), str(fitted_model)]


def test_show_structure_and_density(cif_2y29: Path, ribosome_map: Path):
    state, data = show_structure_and_density(cif_2y29, ribosome_map, renderer="raw")

    expected_data = {
        str(ribosome_map): ribosome_map.read_bytes(),
        str(cif_2y29): cif_2y29.read_bytes(),
    }
    assert data == expected_data
    assert isinstance(state, State)
    assert state.kind == "single"
    assert _child_urls(state.root) == [str(ribosome_map), str(cif_2y29)]
