# coding: utf-8

# flake8: noqa
"""
Programmatic access API endpoints

<p>         Welcome to the interactive documentation page for the         AlphaFold Protein Structure Database Application Programming Interface (API).         The API provides a convenient and efficient way for developers to         programmatically access  metadata related to all the archived AlphaFold         predictions.         </p>         <p>         With this API, you can easily retrieve information about protein structures         predicted by AlphaFold, such as URLs to model files (mmCIF, bCIF and PDB),         models quality estimates, and other useful information. All the API endpoints         are keyed on UniProt accessions. The API is designed to be easy to integrate         into your own software, and we provide documentation and code examples         below to help you get started.</p>

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from protein_detective.alphafold_client.models.annotation import Annotation
from protein_detective.alphafold_client.models.annotation_response import AnnotationResponse
from protein_detective.alphafold_client.models.annotation_type import AnnotationType
from protein_detective.alphafold_client.models.confidence_type import ConfidenceType
from protein_detective.alphafold_client.models.ensemble_sample_format import EnsembleSampleFormat
from protein_detective.alphafold_client.models.entity import Entity
from protein_detective.alphafold_client.models.entity_poly_type import EntityPolyType
from protein_detective.alphafold_client.models.entity_type import EntityType
from protein_detective.alphafold_client.models.entry_summary import EntrySummary
from protein_detective.alphafold_client.models.evidence import Evidence
from protein_detective.alphafold_client.models.experimental_method import ExperimentalMethod
from protein_detective.alphafold_client.models.http_validation_error import HTTPValidationError
from protein_detective.alphafold_client.models.identifier_category import IdentifierCategory
from protein_detective.alphafold_client.models.location_inner import LocationInner
from protein_detective.alphafold_client.models.model_category import ModelCategory
from protein_detective.alphafold_client.models.model_format import ModelFormat
from protein_detective.alphafold_client.models.model_type import ModelType
from protein_detective.alphafold_client.models.oligomeric_state import OligomericState
from protein_detective.alphafold_client.models.overview import Overview
from protein_detective.alphafold_client.models.region import Region
from protein_detective.alphafold_client.models.summary_items import SummaryItems
from protein_detective.alphafold_client.models.uniprot_entry import UniprotEntry
from protein_detective.alphafold_client.models.uniprot_summary import UniprotSummary
from protein_detective.alphafold_client.models.validation_error import ValidationError
