# coding: utf-8

"""
Programmatic access API endpoints

<p>         Welcome to the interactive documentation page for the         AlphaFold Protein Structure Database Application Programming Interface (API).         The API provides a convenient and efficient way for developers to         programmatically access  metadata related to all the archived AlphaFold         predictions.         </p>         <p>         With this API, you can easily retrieve information about protein structures         predicted by AlphaFold, such as URLs to model files (mmCIF, bCIF and PDB),         models quality estimates, and other useful information. All the API endpoints         are keyed on UniProt accessions. The API is designed to be easy to integrate         into your own software, and we provide documentation and code examples         below to help you get started.</p>

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from protein_detective.alphafold_client.models.overview import Overview
from protein_detective.alphafold_client.models.uniprot_entry import UniprotEntry
from typing import Optional, Set
from typing_extensions import Self


class UniprotSummary(BaseModel):
    """
    UniprotSummary
    """  # noqa: E501

    uniprot_entry: Optional[UniprotEntry] = None
    structures: Optional[List[Overview]] = None
    __properties: ClassVar[List[str]] = ["uniprot_entry", "structures"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UniprotSummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of uniprot_entry
        if self.uniprot_entry:
            _dict["uniprot_entry"] = self.uniprot_entry.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in structures (list)
        _items = []
        if self.structures:
            for _item_structures in self.structures:
                if _item_structures:
                    _items.append(_item_structures.to_dict())
            _dict["structures"] = _items
        # set to None if uniprot_entry (nullable) is None
        # and model_fields_set contains the field
        if self.uniprot_entry is None and "uniprot_entry" in self.model_fields_set:
            _dict["uniprot_entry"] = None

        # set to None if structures (nullable) is None
        # and model_fields_set contains the field
        if self.structures is None and "structures" in self.model_fields_set:
            _dict["structures"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UniprotSummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        # raise errors for additional fields in the input
        for _key in obj.keys():
            if _key not in cls.__properties:
                raise ValueError("Error due to additional fields (not defined in UniprotSummary) in the input: " + _key)

        _obj = cls.model_validate(
            {
                "uniprot_entry": UniprotEntry.from_dict(obj["uniprot_entry"])
                if obj.get("uniprot_entry") is not None
                else None,
                "structures": [Overview.from_dict(_item) for _item in obj["structures"]]
                if obj.get("structures") is not None
                else None,
            }
        )
        return _obj
